import genre from "./genre";
import type from "./type";

// tymczas grafiki
import ico1 from "../../images/2019_07_wnetrze_mieszkalne_essen_niemcy_ico.jpg";
import ico1Thumb from "../../images/2019_07_wnetrze_mieszkalne_essen_niemcy_ico__thumb.jpg";
import ico2 from "../../images/2019_08_obiekt_biurowy_leverkusen_niemcy_ico.jpg";
import ico2Thumb from "../../images/2019_08_obiekt_biurowy_leverkusen_niemcy_ico__thumb.jpg";
import ico3 from "../../images/2020_05_osiedle_mieszkaniowe_dormagen_niemcy_ico.jpg";
import ico3Thumb from "../../images/2020_05_osiedle_mieszkaniowe_dormagen_niemcy_ico__thumb.jpg";
import ico4 from "../../images/2020_07_osiedle_mieszkaniowe_aachen_niemcy_ico.jpg";
import ico4Thumb from "../../images/2020_07_osiedle_mieszkaniowe_aachen_niemcy_ico__thumb.jpg";

import image1big from "../../images/2009_02_centrum_hotelowo_kongresowe_wroclaw_polska_001.jpg";
import image1bigThumb from "../../images/2009_02_centrum_hotelowo_kongresowe_wroclaw_polska_001__thumb.jpg";
import image2 from "../../images/2009_02_centrum_hotelowo_kongresowe_wroclaw_polska_002.jpg";
import image2Thumb from "../../images/2009_02_centrum_hotelowo_kongresowe_wroclaw_polska_002__thumb.jpg";
import phoneImage from "../../images/phone_melbeck.png";
import phoneImageThumb from "../../images/phone_melbeck__thumb.jpg";
import panoramaIco from "../../images/2013_08_osiedle_mieszkaniowe_dusseldorf_niemcy_ico01.jpg";
import panoramaIcoThumb from "../../images/2013_08_osiedle_mieszkaniowe_dusseldorf_niemcy_ico01__thumb.jpg";
import panoramaFull from "../../images/2013_08_osiedle_mieszkaniowe_dusseldorf_niemcy_pano02big.jpg";
import panoramaFullThumb from "../../images/2013_08_osiedle_mieszkaniowe_dusseldorf_niemcy_pano02big__thumb.jpg";

export const DUMMY_PROJECTS = [
  {
    id: "1",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl1",
    projNameEn: "projNameEn1",
    completionDate: new Date("2013-11"),
    cityPL: "cityPL1",
    cityEn: "cityEn1",
    countryPL: "countryPL1",
    countryEn: "countryEn1",
    icoImgFull: ico1,
    icoImgThumb: ico1Thumb,
    type: [type.COMPETITION],
  },
  {
    id: "2",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl2",
    projNameEn: "projNameEn2",
    completionDate: new Date("2018-11"),
    cityPL: "cityPL2",
    cityEn: "cityEn2",
    countryPL: "countryPL2",
    countryEn: "countryEn2",
    icoImgFull: ico2,
    icoImgThumb: ico2Thumb,
    type: [type.COMPETITION, type.INTERIOR],
  },
  {
    id: "3",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl3",
    projNameEn: "projNameEn3",
    completionDate: new Date("2020-11"),
    cityPL: "cityPL3",
    cityEn: "cityEn3",
    countryPL: "countryPL3",
    countryEn: "countryEn3",
    icoImgFull: ico3,
    icoImgThumb: ico3Thumb,
    type: [type.COMPETITION, type.INTERIOR, type.EXTERIOR],
  },
  {
    id: "4",
    genre: genre.APP,
    projNamePl: "projNamePl4",
    projNameEn: "projNameEn4",
    completionDate: new Date("2021-4"),
    cityPL: "cityPL4",
    cityEn: "cityEn4",
    countryPL: "countryPL4",
    countryEn: "countryEn4",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [type.COMPETITION, type.INTERIOR, type.EXTERIOR, type.ANIMATION],
  },
  {
    id: "5",
    genre: genre.APP,
    projNamePl: "projNamePl5",
    projNameEn: "projNameEn5",
    completionDate: new Date("2014-4"),
    cityPL: "cityPL5",
    cityEn: "cityEn5",
    countryPL: "countryPL5",
    countryEn: "countryEn5",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
    ],
  },
  {
    id: "6",
    genre: genre.APP,
    projNamePl: "projNamePl7",
    projNameEn: "projNameEn7",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL7",
    cityEn: "cityEn7",
    countryPL: "countryPL7",
    countryEn: "countryEn7",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
    ],
  },
  {
    id: "7",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl6",
    projNameEn: "projNameEn6",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL6",
    cityEn: "cityEn6",
    countryPL: "countryPL6",
    countryEn: "countryEn6",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
      type.APP,
    ],
  },
  {
    id: "8",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl8",
    projNameEn: "projNameEn8",
    completionDate: new Date("2013-11"),
    cityPL: "cityPL8",
    cityEn: "cityEn8",
    countryPL: "countryPL8",
    countryEn: "countryEn8",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [type.COMPETITION],
  },
  {
    id: "9",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl9",
    projNameEn: "projNameEn9",
    completionDate: new Date("2018-11"),
    cityPL: "cityPL9",
    cityEn: "cityEn9",
    countryPL: "countryPL9",
    countryEn: "countryEn9",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [type.COMPETITION, type.INTERIOR],
  },
  {
    id: "10",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl10",
    projNameEn: "projNameEn10",
    completionDate: new Date("2020-11"),
    cityPL: "cityPL10",
    cityEn: "cityEn10",
    countryPL: "countryPL10",
    countryEn: "countryEn10",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [type.COMPETITION, type.INTERIOR, type.EXTERIOR],
  },
  {
    id: "11",
    genre: genre.APP,
    projNamePl: "projNamePl11",
    projNameEn: "projNameEn11",
    completionDate: new Date("2021-4"),
    cityPL: "cityPL11",
    cityEn: "cityEn11",
    countryPL: "countryPL11",
    countryEn: "countryEn11",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [type.COMPETITION, type.INTERIOR, type.EXTERIOR, type.ANIMATION],
  },
  {
    id: "12",
    genre: genre.APP,
    projNamePl: "projNamePl12",
    projNameEn: "projNameEn12",
    completionDate: new Date("2014-4"),
    cityPL: "cityPL12",
    cityEn: "cityEn12",
    countryPL: "countryPL12",
    countryEn: "countryEn12",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
    ],
  },
  {
    id: "13",
    genre: genre.APP,
    projNamePl: "projNamePl13",
    projNameEn: "projNameEn13",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL13",
    cityEn: "cityEn13",
    countryPL: "countryPL13",
    countryEn: "countryEn13",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
    ],
  },
  {
    id: "14",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl14",
    projNameEn: "projNameEn14",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL14",
    cityEn: "cityEn14",
    countryPL: "countryPL14",
    countryEn: "countryEn14",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
      type.APP,
    ],
  },
  {
    id: "15",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl15",
    projNameEn: "projNameEn15",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL15",
    cityEn: "cityEn15",
    countryPL: "countryPL15",
    countryEn: "countryEn15",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
      type.APP,
    ],
  },
  {
    id: "16",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl16",
    projNameEn: "projNameEn16",
    completionDate: new Date("2013-11"),
    cityPL: "cityPL16",
    cityEn: "cityEn16",
    countryPL: "countryPL16",
    countryEn: "countryEn16",
    icoImgFull: ico1,
    icoImgThumb: ico1Thumb,
    type: [type.COMPETITION],
  },
  {
    id: "17",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl17",
    projNameEn: "projNameEn17",
    completionDate: new Date("2018-11"),
    cityPL: "cityPL17",
    cityEn: "cityEn17",
    countryPL: "countryPL17",
    countryEn: "countryEn17",
    icoImgFull: ico2,
    icoImgThumb: ico2Thumb,
    type: [type.COMPETITION, type.INTERIOR],
  },
  {
    id: "18",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl18",
    projNameEn: "projNameEn18",
    completionDate: new Date("2020-11"),
    cityPL: "cityPL18",
    cityEn: "cityEn18",
    countryPL: "countryPL18",
    countryEn: "countryEn18",
    icoImgFull: ico3,
    icoImgThumb: ico3Thumb,
    type: [type.COMPETITION, type.INTERIOR, type.EXTERIOR],
  },
  {
    id: "19",
    genre: genre.APP,
    projNamePl: "projNamePl19",
    projNameEn: "projNameEn19",
    completionDate: new Date("2021-4"),
    cityPL: "cityPL19",
    cityEn: "cityEn19",
    countryPL: "countryPL19",
    countryEn: "countryEn19",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [type.COMPETITION, type.INTERIOR, type.EXTERIOR, type.ANIMATION],
  },
  {
    id: "20",
    genre: genre.APP,
    projNamePl: "projNamePl20",
    projNameEn: "projNameEn20",
    completionDate: new Date("2014-4"),
    cityPL: "cityPL20",
    cityEn: "cityEn20",
    countryPL: "countryPL20",
    countryEn: "countryEn20",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
    ],
  },
  {
    id: "21",
    genre: genre.APP,
    projNamePl: "projNamePl21",
    projNameEn: "projNameEn21",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL21",
    cityEn: "cityEn21",
    countryPL: "countryPL21",
    countryEn: "countryEn21",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
    ],
  },
  {
    id: "22",
    genre: genre.GRAPHIC,
    projNamePl: "projNamePl22",
    projNameEn: "projNameEn22",
    completionDate: new Date("2012-4"),
    cityPL: "cityPL22",
    cityEn: "cityEn22",
    countryPL: "countryPL22",
    countryEn: "countryEn22",
    icoImgFull: ico4,
    icoImgThumb: ico4Thumb,
    type: [
      type.COMPETITION,
      type.INTERIOR,
      type.EXTERIOR,
      type.ANIMATION,
      type.PRODUCT_MODELING,
      type.PANORAMA,
      type.APP,
    ],
  },
];

export const DUMMY_PROJECT_PANORAMA = {
  id: "1",
  genre: genre.PANORAMA,
  projNamePl: "OSIEDLE MIESZKANIOWE",
  projNameEn: "HOUSING ESTATE",
  completionDate: new Date("2013-11"),
  cityPL: "DÜSSELDORF",
  cityEn: "DÜSSELDORF",
  countryPL: "NIEMCY",
  countryEn: "GERMANY",
  clientPL: "VIRTUELL FORMAT",
  clientEn: "VIRTUELL FORMAT",
  icoImgFull: ico1,
  icoImgThumb: ico1Thumb,
  type: [type.PANORAMA],
  panoramas: [
    {
      panoramaTitle: "PANORAMA_1",
      panoramaIcoFull: panoramaIco,
      panoramaIcoThumb: panoramaIcoThumb,
      panoramaImageSourceFull: panoramaFull,
      panoramaImageSourceFullThumb: panoramaFullThumb,
    },
    {
      panoramaTitle: "PANORAMA_2",
      panoramaIcoFull: panoramaIco,
      panoramaIcoThumb: panoramaIcoThumb,
      panoramaImageSourceFull: panoramaFull,
      panoramaImageSourceFullThumb: panoramaFullThumb,
    },
    {
      panoramaTitle: "PANORAMA_3",
      panoramaIcoFull: panoramaIco,
      panoramaIcoThumb: panoramaIcoThumb,
      panoramaImageSourceFull: panoramaFull,
      panoramaImageSourceFullThumb: panoramaFullThumb,
    },
  ],
};

export const DUMMY_PROJECT_GRAPHIC = {
  id: "1",
  genre: genre.GRAPHIC,
  projNamePl: "CENTRUM HOTELOWO-KONGRESOWE CUPRUM",
  projNameEn: "HOTEL/CONGRESS CENTRE CUPRUM",
  completionDate: new Date("2009-11"),
  cityPL: "WROCŁAW",
  cityEn: "WROCLAW",
  countryPL: "POLSKA",
  countryEn: "POLAND",
  clientPL: "HERMANOWICZ REWSKI ARCHITEKCI",
  clientEn: "HERMANOWICZ REWSKI ARCHITECTS",
  icoImgFull: ico1,
  icoImgThumb: ico1Thumb,
  type: [type.COMPETITION],
  images: [
    {
      imageSourceFull: image1big,
      imageSourceThumb: image1bigThumb,
      imageAltPl: "Hall hotelu.",
      imageAltEn: "Lounge of the hotel.",
      isBig: true,
    },
    {
      imageSourceFull: image2,
      imageSourceThumb: image2Thumb,
      imageAltPl: "Przekrój.",
      imageAltEn: "Cross-section.",
      isBig: false,
    },
  ],
};

export const DUMMY_PROJECT_ANIMATION = {
  id: "1",
  genre: genre.ANIMATION,
  projNamePl: "OSIEDLE MIESZKANIOWE",
  projNameEn: "HOUSING ESTATE",
  completionDate: new Date("2017-11"),
  cityPL: "DÜSSELDORF",
  cityEn: "DÜSSELDORF",
  countryPL: "NIEMCY",
  countryEn: "GERMANY",
  clientPL: "VIRTUELL FORMAT",
  clientEn: "VIRTUELL FORMAT",
  icoImgFull: ico1,
  icoImgThumb: ico1Thumb,
  type: [type.COMPETITION],
  videoSource: "https://www.youtube.com/embed/ljUUT4BJ_7M",
  videoSourceThumb: image1bigThumb,
};

export const DUMMY_PROJECT_APP = {
  id: "1",
  genre: genre.APP,
  projNamePl: "BUDYNEK MIESZKALNY - APLIKACJA AR",
  projNameEn: "RESIDENTIAL BUILDING - AR APPLICATION",
  completionDate: new Date("2019-11"),
  cityPL: "DÜSSELDORF",
  cityEn: "DÜSSELDORF",
  countryPL: "NIEMCY",
  countryEn: "GERMANY",
  clientPL: "VIRTUELL FORMAT",
  clientEn: "VIRTUELL FORMAT",
  icoImgFull: ico1,
  icoImgThumb: ico1Thumb,
  type: [type.APP],
  appInfo: {
    appNamePl: "VILLA MELBECK",
    appNameEn: "VILLA MELBECK",
    appImageFull: phoneImage,
    appImageThumb: phoneImageThumb,
    appDescriptionPl:
      "Aplikacja mobilna VILLA MELBECK to prezentacja modelu 3d za pomocą technologii Augmented Reality. Gdy skierują Państwo kamerę swojego telefonu na wydrukowany wcześniej plan zagospodarowania terenu (zawarty w aplikacji w formie PDF'a), pojawi się na ekranie model trójwymiarowy budynku.",
    appDescriptionEn:
      "Mobile application VILLA MELBECK is a presentation of 3d model with Augmented Reality technology. When you point your mobile phone camera at printed land development plan (available within the application in PDF format), you will see 3dimensional model of provided building.",
    appAndroidLink:
      "https://play.google.com/store/apps/details?id=com.vf.dus160",
    appIOSLink: "https://itunes.apple.com/us/app/xantenerstr-12/id1456387858",
  },
};
